### ISSUE TITLE
consider dropping dependency on unmaintained soup-sys crate

### ISSUE THREAD

**Issue by decathorpe** [tauri-apps/webkit2gtk-rs#113]
The soup-sys crate - a dependency of the webkit2gtk-sys crate - has been unmaintained for a while. The GitHub project is now archived and read-only: https://github.com/gtk-rs/soup-sys-rs

There are even some bugs in the bindings (for example, some constants from C are not defined correctly, as witnessed by the failing test suite), which might even impact functionality or security of the crate, since it affects the calculation of cookie age.

Additionally, soup-sys still requires the 0.10 gtk-rs stack, whereas everything else depends on the 0.14 stack, leading to duplicated dependencies on the gtk-rs stack in everything that uses both soup-sys and other gtk-rs crates. I'm not even sure how that works, since both glib-sys 0.10 and glib-sys 0.14 link against system glib library ....

I tried fixing those issues here (even though the master / crate branch split is really weird to work with):

- https://github.com/gtk-rs/soup-sys-rs/pull/24
- https://github.com/gtk-rs/soup-sys-rs/pull/25

However, the project was marked unmaintained and archived before my PRs were merged.

Alternatively, if dropping the dependency is not an option, please consider taking over maintenance of soup-sys as well, considering that you took webkit2gtk bindings too, and soup bindings are a dependency of those. In that case, feel free to reuse my PR to bring soup-sys up-to-date.

**Comment by wusyong** [comment]
Hey, sorry for the late reply. I was working on audit around tauri lately.
I also got some messages from gtk-rs. So apparently both soup2 wrapper crates from gtk-rs and gnome community are outdated.
Gnome does have soup3 crate thanks to @vhdirk. But I think most distro's webkitgtk still use soup2.

I'll add a soup2 crate soon. And once it's published and this crate can use it, I'll update the minor version of this crate and yank the versions that have breaking changes reported from #114. It's webkit2gtk 0.15.3 and webkit2gtk-sys 0.15.2 right?

**Comment by decathorpe** [comment]
Yeah, the situation is a bit messy. Thanks for investigating.

webkit2gtk 0.15.3 / webkit2gtk-sys 0.15.2 are the crate versions that seem to have breaking changes in them.

**Comment by vhdirk** [comment]
Not at my computer right now, but if my memory serves me right, my soup2 fork should be pretty usable. https://github.com/vhdirk/soup-rs

**Comment by wusyong** [comment]
@vhdirk Wow this is amazing! The Gir.toml of normal mode is going to help a lot.

**Comment by decathorpe** [comment]
You might also want to look at my PRs, in particular the one for the "crate" branch, which updates it to match the current gtk-rs 0.14 stack ... right now, webkit2gtk-rs pulls in parts of both gtk-rd 0.14 and 0.10 stacks.

**Comment by wusyong** [comment]
We published 0.16 and it should use the new published soup2 crate.
I'll try to move soup2 crate to gnome or gtk-rs if one of them is willing to maintain again.
