### ISSUE TITLE
How to integrate a Rust native app using webkit2gtk and a Rust webservice using actix-web into one app

### ISSUE THREAD

**Issue by 12a6** [tauri-apps/webkit2gtk-rs#141]
**Is your feature request related to a problem?** 

Is it feasible to merge a Rust native app using webkit2gtk and a Rust webservice using actix-web into one app?

I wonder whether there's a solution that:
1. `cargo run` will start my Rust webservice using actix-web & show Webview from a Rust native app using webkit2gtk together (Only one project with 1 main() fn to trigger starting of both parts)
2. Then if User close GUI window, both parts would be terminated 

P/S: I'm new in Rust, I'm sorry for any inconveniences.
Thanks

**Comment by FabianLars** [comment]
It should possible but to be honest i'd suggest using https://github.com/tauri-apps/wry (or even tauri) for this as it will be much much easier as it handles windowing and the event loop itself, especially for rust beginners.

If you don't want that, take a look at the repo example, basically all you need to do is spawn the actix runtime in a separate thread (webkitgtk/gtk should run on the main thread if possible). The thread should automatically be killed when your app exits but you could manually shut it down (if you need clean up of a "safe" exit) on the app exit event.

**Comment by 12a6** [comment]
@FabianLars: Thank  you so much
Based on your reply, finally I can resolve my problems.
I referred also code snippets on
https://stackoverflow.com/questions/75386470/running-an-actix-web-server-on-a-separate-thread
