### ISSUE TITLE
Rust Webview JavaScript interface

### ISSUE THREAD

**Issue by 12a6** [tauri-apps/webkit2gtk-rs#142]
**Is your feature request related to a problem? Please describe.**
I am developing a Web plug-in of Rust native app (Plug-in will be loaded into a Webview instance of native Rust app). My plug-in must fetch ( via GET/POST/PUT/DELETE requests) data from remote servers. Currently, my Web plug-in could not use default JavaScript fetch due to blocking by CORS errors. Therefore, I must find a way to call fetch handlers from Rust native app. 

**Describe the solution you'd like**

I know that Android apps can expose JavaScript interface APIs to web plugins (run inside a Webview).

I would like to ask: How can Rust native apps expose JavaScript interface APIs to web plugins (run inside a Webview)" ?
Thanks

**Comment by FabianLars** [comment]
This recent blog post may be interesting for you: https://wpewebkit.org/blog/06-integrating-wpe.html

We currently use the same APIs in Wry/Tauri to power our JS<->Rust communication. Wry may be a helpful resource here too, to see how that C code may translate to Rust.
