### ISSUE TITLE
Devtools appereance

### ISSUE THREAD

**Issue by EndorFlem** [tauri-apps/webkit2gtk-rs#148]
Maybe this is a stupid question. Is there a way to change devtools appearance ?

**Comment by amrbashir** [comment]
I don't think so, it probably follows the gtk theme of the hosting window. I think you should ask in a gtk community like this one maybe https://matrix.to/#/#rust:gnome.org.

anyways, since this crate is just a binding crate, I will go ahead and close the issue.
