### ISSUE TITLE
Forbid unsafe code

### ISSUE THREAD

**Issue by thief-sty** [tauri-apps/webkit2gtk-rs#158]
Hi. Should this crate use `#![forbid(unsafe_code)]`? Could we add it now or should some steps be taken before that?

**Comment by FabianLars** [comment]
Ignoring that most of the crate(s) is autogenerated, isn't that virtually impossible for FFI crates?

**Comment by thief-sty** [comment]
That's what I'd think too but this one doesn't use unsafe code, so I figured I'd ask anyway.

**Comment by FabianLars** [comment]
It does use unsafe code in almost every file. Are you maybe in the wrong repo? Or am i misunderstanding something? I'm super out of the loop when it comes to the webkitgtk bindings tbh.

**Comment by thief-sty** [comment]
Sorry, two things went wrong here on my part.
- I was specifically referring to the `webkit2gtk-sys` crate, not `webkit2gtk`. Should have checked the whole repo beforehand.
- Although cargo-geiger does mark `webkit2gtk-sys` as not using `unsafe`, the keyword does appear many times in the source code. It seems to always be in declarations, so I'm not sure how that'd work with `#![forbid(unsafe_code)]`.

Again sorry for the potential waste of time.
