### ISSUE TITLE
Crate is missing `Ext` traits?

### ISSUE THREAD

**Issue by ghost** [tauri-apps/webkit2gtk-rs#93]
On both the latest release, v0.14.0, and my best attempts to update the `master` branch (see: #89), this crate is missing all `Ext` traits, including `SettingsExt`, `WebContextExt`, and `WebViewExt`.
Apologies if there's a reason for this that I'm missing, I'd really like some clarification and help. I'm not that familiar with the inner-workings and development of the GTK-rs project, I'm just trying to use it

**Comment by jangernert** [comment]
Did you import `use webkit2gtk::traits::*;` ?

**Comment by ghost** [comment]
Hey @jangernert, I didn't see your reply. I've pushed a new commit to #89 where I've resolved this issue. I simply made the traits public in [`src/auto/mod.rs`](https://github.com/EmmyGH/webkit2gtk-rs/blob/23f54b7ce79b8eac627e6343d07f6563f5fb70ab/src/auto/mod.rs), as they were in v0.11.0.

**Comment by ergpopler** [comment]
This still doesn't show up in the documentation :angry:
